---
# file: group_vars/all

alt_ssh_port: 4126
ansible_python_interpreter: /usr/bin/python2.7
httpd_group: www-data

swapfile_path: /swapfile
swapfile_size: 1024  #1024 #'{{ ansible_memtotal_mb * 2 }}' M bytes

ntp_servers:
  - ntp1.sakura.ad.jp
  - ntp.nict.jp

#openssl passwd -1 hogehoge
users:
  - { name: admin,  password: "1$JpAWXVtv$zTBLMOh.fTP5V3pakL74c0", groups: "sudo,adm" }
  - { name: auser,  password: "1$JpAWXVtv$zTBLMOh.fTP5V3pakL74c0", groups: "sudo,adm" }

virtualhosts:
  - { name: test1.virtual.net , master: "admin", use_home: True}
  - { name: test2.virtual.net , master: "auser", use_home: False}

mysql_root_password: pass

wordpresses:
  - {
    site: "test1.virtual.net" ,
    master: "admin",
    db_host: "localhost",
    db_name: "test1_wp",
    db_user: "test1_user",
    db_pass: "test1",
  }
  - {
    site: "test2.virtual.net" ,
    master: "auser",
    db_host: "localhost",
    db_name: "test2_wp",
    db_user: "test2_user",
    db_pass: "test2",
  }
