---
# file: group_vars/all

alt_ssh_port: 4126
ansible_python_interpreter: /usr/bin/python2.7
httpd_group: www-data

swapfile_path: /swapfile
swapfile_size: 1024  #1024 #'{{ ansible_memtotal_mb * 2 }}' M bytes

ntp_servers:
  - ntp1.sakura.ad.jp
  - ntp.nict.jp

#openssl passwd -1 'hogehoge'
users:
  - { name: admin,  password: "1$JpAWXVtv$zTBLMOh.fTP5V3pakL74c0", groups: "sudo,adm" }
  - { name: auser,  password: "1$JpAWXVtv$zTBLMOh.fTP5V3pakL74c0", groups: "sudo,adm" }

virtualhosts:
  - name: test1.virtual.net
    master: "admin"
    use_home: True
    names:
      - staging.virtual.net
      - develop.virtual.net
  - name: test2.virtual.net
    master: "auser"
    use_home: False
    names: []

mysql_root_password: pass

wordpresses:
  # - name: "WordPress Site 1"
  #   url_scheme: 'http'
  #   url_host: 'test1.virtual.net'   #don't add / at end
  #   url_sub: 'wordpress' #don't add / at end
  #   title: 'WordPress Site 1'
  #   wp_dir: "/home/admin/public/www/sites/test1.virtual.net/html/wordpress"
  #   master: "admin"  #linux user name for web master
  #   wp_admin: "wp_admin1"
  #   wp_admin_pass: "wp_pass1"
  #   wp_admin_email: "admin@test1.virtual.net"
  #   Languages:
  #     - ja
  #   #db
  #   dbhost: "localhost"
  #   dbname: "test1_wp"
  #   dbuser: "test1_user"
  #   dbpass: "test1"
  #   dbprefix: "w1p_"

  # - name: 'WordPress Site 2'
  #   url_scheme: 'http'
  #   url_host: 'test2.virtual.net'
  #   url_sub: 'wordpress'
  #   title: 'WordPress Site 2'
  #   wp_dir: "/var/www/sites/test2.virtual.net/html/wordpress"
  #   master: "auser"
  #   wp_admin: "wp_admin2"
  #   wp_admin_pass: "wp_pass2"
  #   wp_admin_email: "admin2@test2.virtual.net"
  #   Languages: []
  #   #db
  #   dbhost: "localhost"
  #   dbname: "test2_wp"
  #   dbuser: "test2_user"
  #   dbpass: "test2"
  #   dbprefix: "w2p_"

