---
# tasks file for install nginx
# https://www.nginx.com/blog/installing-nginx-nginx-plus-ansible/

- name: NGINX | Adding NGINX signing key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  tags: nginx

- name: NGINX | Adding sources.list deb url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
  tags: nginx

- name: NGINX Plus | Adding sources.list deb-src url for NGINX
  lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/mainline/ubuntu/ trusty nginx"
  tags: nginx

- name: NGINX | Updating apt cache
  apt:
    update_cache: yes
  tags: nginx

- name: NGINX | Installing NGINX
  apt:
    pkg: nginx
    state: latest
  tags: nginx

- name: NGINX | Ensures snipet dir
  file: path=/etc/nginx/snippets state=directory
  tags: nginx

- name: NGINX | Installing Snipet files
  copy: src="fastcgi-php.conf" dest="/etc/nginx/snippets/fastcgi-php.conf" mode=0744 directory_mode=yes
  notify: restart nginx
  tags: nginx

- copy: src="fastcgi.conf" dest="/etc/nginx/fastcgi.conf" mode=0744 directory_mode=yes
  notify: restart nginx
  tags: nginx

- name: NGINX | open http/https port
  ufw: rule=allow port={{item}} proto=tcp
  with_items: ['http','https']
  tags: nginx

- name: give access right for NGINX
  user: name=nginx groups={{httpd_group}} append=yes
  notify: restart nginx
  tags:
    - nginx
