---
# tasks file for virtual hosts

- name: NGINX | Create virtual host configuration directory
  file: path='{{ item }}' state=directory owner=root group=root mode=0755
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
    - /var/www/sites
  tags: nginx

- name: NGINX | Include virtual host configuration
  lineinfile: >
    dest=/etc/nginx/nginx.conf
    insertafter="/etc/nginx/conf\.d/\*\.conf"
    line="    include /etc/nginx/sites-enabled/*;"
    state=present
    backup=yes
  tags: nginx

- name: Create virtual host definition
  template: src=virtualhost.conf.j2 dest=/etc/nginx/sites-available/{{item.name}}
  with_items: '{{ virtualhosts }}'
  tags: nginx

- name: Enable virtual hosts
  file: src=/etc/nginx/sites-available/{{item.name}} dest=/etc/nginx/sites-enabled/{{item.name}} state=link
  with_items: '{{ virtualhosts }}'
  tags: nginx

- name: NGINX | Create virtual host contain directory
  file: path='/var/www/sites' state=directory owner=root group=root mode=0755
  tags: nginx

- name: NGINX | Create virtual host contain directory for home
  file: >
    path='/home/{{item[1].master}}{{item[0]}}' state=directory
    owner={{item[1].master}} group={{httpd_group}} mode=0775
  with_nested:
    - ['/public','/public/www','/public/www/sites']
    - '{{ virtualhosts }}'
  when: item[1].use_home == True
  tags: nginx

- name: Create virtual host content folders
  file: >
    path='/var/www/sites/{{ item[1].name }}{{item[0]}}' state=directory
    owner={{item[1].master}} group={{httpd_group}} mode=0775
  with_nested:
    - ['','/html']
    - '{{ virtualhosts }}'
  when: item[1].use_home != True
  tags: nginx

- name: Create virtual host content folders for home
  file: >
    path='/home/{{item[1].master}}/public/www/sites/{{ item[1].name }}{{item[0]}}' state=directory
    owner={{item[1].master}} group={{httpd_group}} mode=0775
  with_nested:
    - ['','/html']
    - '{{ virtualhosts }}'
  when: item[1].use_home == True
  tags: nginx

- name: Link home to nginx document root
  file: >
    src='/home/{{item.master}}/public/www/sites/{{item.name}}'
    dest='/var/www/sites/{{item.name}}'
    state=link owner={{item.master}} group={{httpd_group}}
  with_items: '{{ virtualhosts }}'
  when: item.use_home == True
  tags: nginx

- name: Put virtual host test index.php
  template: >
    src=index.php.j2 dest=/var/www/sites/{{item.name}}/html/index.php
    owner={{item.master}} group={{httpd_group}} mode=0775
  with_items: '{{ virtualhosts }}'
  tags: nginx
