- name: setup ansible component
  hosts: init
  gather_facts: no
  tasks:
    - name: install python2.7
      raw: if [ ! -e {{ ansible_python_interpreter }} ]; then sudo apt-get update && sudo apt-get install -y python2.7; fi

