---
# ansible-playbook -i hosts ansible_init.yml
- name: setup ansible component
  hosts: init
  gather_facts: no
  tasks:
    - name: install python2.7
      raw: if [ ! -e {{ ansible_python_interpreter }} ]; then sudo apt-get update && sudo apt-get install -y python2.7; fi

- name: setup SSH
  hosts: init
  tasks:
    - name: change SSH port to {{ alt_ssh_port }}
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port {{ alt_ssh_port }}"

    - name: disable password login
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: disable root login
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin.*"
        line: "PermitRootLogin no"

    - name: sshd restart
      become: yes
      become_user: root
      service: name=sshd state=restarted
