---
# please connect host by ssh befor ansible
#  for set host as knownhost
# ansible-playbook -i hosts ansible_init.yml

# - name: setup ansible component
#   hosts: init
#   vars:
#     ansible_port: 22
#   gather_facts: no
#   tasks:
#     - name: apt update
#       raw: sudo apt-get update -qq
#     - name: install python2.7
#       raw: sudo apt-get install -qq python2.7

- name: setup SSH
  hosts: init
  vars:
    ansible_port: 22
  tasks:
    - name: create ~/.ssh for ansible
      file: path="/home/{{ansible_user}}/.ssh" state=directory owner={{ansible_user}} group={{ansible_user}} mode=0700
    - name: copy authorized key
      copy: src="keys/id_rsa_{{ansible_user}}.pub" dest="/home/{{ansible_user}}/.ssh/authorized_keys" owner={{ansible_user}} group={{ansible_user}} mode=0600

    - name: change SSH port to {{ alt_ssh_port }}
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        line: "Port {{ alt_ssh_port }}"

    - name: disable password login
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PasswordAuthentication"
        line: "PasswordAuthentication no"

    - name: disable root login
      become: yes
      become_user: root
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^PermitRootLogin.*"
        line: "PermitRootLogin no"

    - name: sshd restart
      become: yes
      become_user: root
      service: name=sshd state=restarted
