---
# file: webservers.yml
# see: http://knowledge.sakura.ad.jp/tech/3084/
- name: setup Web server
  hosts: webservers
  vars:
    ansible_port: "{{ alt_ssh_port }}"
    ansible_ssh_private_key_file: keys/id_rsa_{{ansible_user}}
  become: yes
  become_user: root
  roles:
    - common
    - security
    - nginx
    - php
    - mysql
    - wordpress
    - phantomjs
