---
# file: webservers.yml
# see: http://knowledge.sakura.ad.jp/tech/3084/
- name: setup Web server
  hosts: webservers
  vars:
    ansible_port: "{{ alt_ssh_port }}"
  become: yes
  become_user: root
  roles:
    - common
    - security
    - nginx
    - php
    - mysql
#    - wordpress
