---
# tasks file for wordpress
#

- name: WordPress | download wp-cli
  get_url: url=https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest=/usr/local/bin/wp validate_certs=no mode=0755
  tags:
    - wordpress
    - wp-cli

- name: WordPress | Ensures nginx global dir
  file: path=/etc/nginx/global state=directory
  tags:
    - wordpress

- name: WordPress | Copy nginx config files
  template: src=site.wordpress.j2 dest=/etc/nginx/sites-available/{{item.url_host}}.wordpress
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Nginx settings
  lineinfile: >
    dest=/etc/nginx/sites-available/{{item.url_host}}
    insertbefore="^}"
    line="    include sites-available/{{item.url_host}}.wordpress;"
  with_items: '{{wordpresses}}'
  tags:
    - wordpress
