---

# create new wordpress

- name: WordPress | Ensure wordpress folder
  file: path={{item.wp_dir}} state=directory
    owner={{item.master}} group={{httpd_group}} mode=0775
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | download WordPress
  become: yes
  become_user: '{{item.master}}'
  shell: wp core download
    chdir='{{item.wp_dir}}/'
    creates="{{item.wp_dir}}/index.php"
  with_items: "{{wordpresses}}"
  tags:
    - wordpress

- name: WordPress | Create WordPress Database
  mysql_db: name={{item.dbname}} state=present encoding=utf8
    login_user=root login_password={{mysql_root_password}}
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Create WordPress Database User
  mysql_user: name={{item.dbuser}} password={{item.dbpass}} priv={{item.dbname}}.*:ALL
    state=present login_user=root login_password={{mysql_root_password}}
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Configure WordPress Database
  become: yes
  become_user: '{{item.master}}'
  shell: wp core config --dbname={{item.dbname}} --dbuser={{item.dbuser}} --dbpass={{item.dbpass}} --dbhost={{item.dbhost}}
    chdir={{item.wp_dir}} creates={{item.wp_dir}}/wp-config.php
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Configure WordPress General Settings
  become: yes
  become_user: '{{item.master}}'
  shell: wp core install --url={{item.url_scheme}}://{{item.url_host}}/{{item.url_sub}} --title="{{item.title}}" --admin_user={{item.wp_admin}} --admin_password={{item.wp_admin_pass}} --admin_email={{item.wp_admin_email }}
    chdir={{ item.wp_dir }}
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Configure Permalink
  become: yes
  become_user: '{{item.master}}'
  shell: wp rewrite structure '%postname%'
    chdir={{ item.wp_dir }}
  with_items: '{{wordpresses}}'
  tags:
    - wordpress

- name: WordPress | Install Languages
  become: yes
  become_user: '{{item.0.master}}'
  shell: wp core language install {{item.1}} --path={{ item.0.wp_dir }}
    chdir={{ item.0.wp_dir }} creates={{item.0.wp_dir}}/wp-content/languages/{{item.1}}.mo
  with_subelements:
    - '{{wordpresses}}'
    - Languages
  tags:
    - wordpress
