- name: check SSH port
  wait_for: port=22 host="{{ ansible_ssh_host }}" connect_timeout=2 timeout=2 state="started"
  ignore_errors: True
  register: default_ssh

- name: use default port
  set_fact:
    available_ssh_port: 22
  when: default_ssh is defined and default_ssh.state == "started"

- name: use altanative port
  set_fact:
    # see group_vars/all.yml
    available_ssh_port: "{{ alt_ssh_port }}"
  when: default_ssh is defined and default_ssh.state is undefined

- name: set port to {{ available_ssh_port }}
  set_fact:
    ansible_port: "{{ available_ssh_port }}"
