---
# tasks file for mysql
# http://techwatch.keeward.com/geeks-and-nerds/properly-install-mysql-on-production-server-using-ansible/

- name: Set MySQL root password before installing
  debconf: >
    name='mysql-server'
    question='{{item}}'
    value='{{mysql_root_password | quote}}'
    vtype='password'
  with_items: ['mysql-server/root_password','mysql-server/root_password_again']
  tags:
    - mysql

- name: Install MySQL
  apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
  with_items:
    - mysql-server
    - mysql-client
  tags:
    - mysql

- name: Deletes anonymous MySQL server user for localhost
  mysql_user: user="" state="absent" login_password="{{ mysql_root_password }}" login_user=root
  tags:
    - mysql

- name: Secures the MySQL root user
  mysql_user: user="root" password="{{ mysql_root_password }}" host="{{ item }}" login_password="{{mysql_root_password}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1
    - "{{ ansible_fqdn }}"
  tags:
    - mysql

- name: Removes the MySQL test database
  mysql_db: db=test state=absent login_password="{{ mysql_root_password }}" login_user=root
  tags:
    - mysql
