---

- name: mail | Installing mailutils
  apt:
    pkg: mailutils
  tags: mail

# - name: disable the delivery of non-local mail
#   lineinfile: >
#     dest=/etc/postfix/main.cf
#     create=yes
#     regexp="^default_transport ="
#     line="default_transport = error:outside mail is not deliverable"
#   tags: mail

- name: mail | sendonly setting
  template: >
    src=main.cf.j2 dest=/etc/postfix/main.cf
    backup=yes
  notify:
    - update aliases.db
    - reload aliases
  tags: mail


- name: root alias
  lineinfile: >
    dest=/etc/aliases
    line="root: {{mail_root_alias}}"
  when: mail_root_alias is defined
  notify:
    - update aliases.db
    - reload aliases
  tags: mail
