---

- name: mail | Installing mailutils
  apt:
    pkg: mailutils
  tags: mail

# - name: disable the delivery of non-local mail
#   lineinfile: >
#     dest=/etc/postfix/main.cf
#     create=yes
#     regexp="^default_transport ="
#     line="default_transport = error:outside mail is not deliverable"
#   tags: mail

- name: mail | sendonly setting
  template: >
    src=main.cf.j2 dest=/etc/postfix/main.cf
    backup=yes
  tags: mail


- name: root alias
  lineinfile: >
    dest=/etc/aliases
    line="root: {{mail_root_alias}}"
  when: mail_root_alias is defined
  tags: mail

- name: update aliases.db
  shell: /usr/sbin/postalias /etc/aliases
  tags: mail

- name: reload aliases
  shell: /usr/bin/newaliases
  tags: mail
