- name: hostname
  template: >
    src=hostname.j2 dest=/etc/hostname
    backup=yes
  tags: network

- name: register my certificate filr
  shell: "hostname --file /etc/hostname"
  tags: network

- name: get hostname
  shell: "hostname"
  register: result
  tags: network

- name: result of hostname
  debug: msg="{{ result }}"
  tags: network

- name: add hostname to hosts
  lineinfile: dest=/etc/hosts state=present create=yes regexp="{{result.stdout}}" line="127.0.0.1 {{result.stdout}}"
  tags: network

- name: add my certificate files
  copy: src="{{ item }}" dest="/usr/local/share/ca-certificates/"
  with_fileglob: "../../keys/*.crt"
  tags: network

- name: register my certificate filr
  shell: "update-ca-certificates"
  tags: network



- name: sshd restart
  service: name=networking state=restarted
  tags: network
