---


- name: create swap
  command: dd if=/dev/zero of={{swapfile_path}} bs=1M count={{ ansible_memtotal_mb * 2 }}
  register: create_swapfile
  when: swapfile_path is defined

- file: path={{swapfile_path}} mode=600
  when: swapfile_path is defined

- command: mkswap {{swapfile_path}}
  register: make_swapfile
  when: swapfile_path is defined and create_swapfile.changed

- command: swapon {{swapfile_path}}
  when: swapfile_path is defined and  make_swapfile.changed

- mount:
    name: swap
    src: '{{ swapfile_path }}'
    fstype: swap
    opts: defaults
    passno: '0'
    dump: '0'
    state: present
  when: swapfile_path is defined and
