- name: create working user(s)
  user: name={{item.name}} state=present password={{item.password}} groups={{item.groups}} shell=/bin/bash
  with_items: "{{users}}" #group_vars/all.yml
  tags: users

- name: create ~/.ssh for users
  file: path="/home/{{item.name}}/.ssh" state=directory owner={{item.name}} group={{item.name}} mode=0700
  with_items: "{{users}}"
  tags: users

# run on management server
# pb > mkdir keys ; cd keys
# pb > ssh-keygen -t rsa -f ./id_rsa_{{item.name}}
# $$> ssh {{item.name}}@{{hostname or ip}} -p {{alt_ssh_port}} -i pathto/keys/id_rsa_{{item.name}}
# ex> ssh admin@192.168.33.12 -p 4126 -i ./src/playbooks_xenial64/keys/id_rsa_admin
- name: authorized keys is deployed
  copy: src="../../keys/id_rsa_{{item.name}}.pub" dest="/home/{{item.name}}/.ssh/authorized_keys" owner={{item.name}} group={{item.name}} mode=0600
  with_items: "{{users}}"
  tags: users

- name: copy .bash_profile
  copy: src="default_bash_profile" dest="/home/{{item.name}}/.bash_profile" owner={{item.name}} group={{item.name}} mode=0644
  with_items: "{{users}}"
  tags: users

- name: Ensure /etc/sudoers.d directory is present
  file: path=/etc/sudoers.d state=directory
  tags: users

- name: Ensure /etc/sudoers.d is scanned by sudo
  action: lineinfile dest=/etc/sudoers regexp="#includedir\s+/etc/sudoers.d" line="#includedir /etc/sudoers.d"
  tags: users

- name: Add user to the sudoers
  action: 'lineinfile dest=/etc/sudoers.d/{{item.name}} state=present create=yes regexp="{{item.name}} .*" line="{{item.name}} ALL=(ALL) NOPASSWD: ALL"'
  with_items: "{{users}}"
  tags: users

- name: Ensure /etc/sudoers.d/* file has correct permissions
  action: file path=/etc/sudoers.d/{{item.name}} mode=0440 state=file owner=root group=root
  with_items: "{{users}}"
  tags: users
